In [1]:
import pandas as pd
import json
import requests
import numpy as np
from pprint import pprint
from pymongo import MongoClient

In [2]:
#################################################
# Database Setup
#################################################
mongo = MongoClient(port=27017)

db = mongo['rental_data']
rental_information = db['canadian_rental_market']

In [4]:
query = {'Location.Province': 'Nfld.Lab.'}
df = pd.json_normalize(rental_information.find(query))
df.head()

,_id,id,DwellingType,Year,Location.Province,Location.Center,Location.Zone,Location.Neighbourhood,Location.Geo.lat,Location.Geo.lon,...,RentalInformation.VacancyRate.Bachelor,RentalInformation.VacancyRate.1br,RentalInformation.VacancyRate.2br,RentalInformation.VacancyRate.3br+,RentalInformation.VacancyRate.Total,RentalInformation.NumberofUnits.Bachelor,RentalInformation.NumberofUnits.1br,RentalInformation.NumberofUnits.2br,RentalInformation.NumberofUnits.3br+,RentalInformation.NumberofUnits.Total
0,647e1767ae244ac30b12da0a,1001,Apt & Other,2018,Nfld.Lab.,St. John's,St. John's East,St. John's East,47.56147,-52.712616,...,0.0,3.9,6.4,5.2,5.6,203.0,641.0,1015.0,107.0,1966.0
1,647e1767ae244ac30b12da0b,1002,Row,2018,Nfld.Lab.,St. John's,St. John's West,St. John's West,47.56147,-52.712616,...,0.0,0.0,0.0,0.0,1.5,0.0,46.0,21.0,0.0,67.0
2,647e1767ae244ac30b12da0c,1000,Row,2018,Nfld.Lab.,St. John's,St. John's East,St. John's East,47.56147,-52.712616,...,0.0,0.0,0.0,0.0,0.0,1.0,22.0,16.0,16.0,55.0
3,647e1767ae244ac30b12da0e,1003,Apt & Other,2018,Nfld.Lab.,St. John's,St. John's West,St. John's West,47.56147,-52.712616,...,3.9,6.1,6.1,0.0,6.2,149.0,427.0,859.0,126.0,1561.0
4,647e1767ae244ac30b12da18,1005,Apt & Other,2018,Nfld.Lab.,St. John's,Remainder of CMA,Remainder of CMA,47.56147,-52.712616,...,0.0,4.5,0.0,0.0,0.0,7.0,147.0,182.0,63.0,399.0

In [29]:
query = {'Location.Province': 'Alta' }

pprint(list(rental_information.find(query).distinct("Location.Center")))

['Calgary', 'Edmonton', 'Lethbridge']